import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiPhone,
  HiMapPin,
  HiOutlineAcademicCap,
  HiOutlineBriefcase,
  HiOutlineServerStack,
  HiOutlineCodeBracket,
  HiOutlineCpuChip,
  HiOutlineLanguage,
  HiOutlineHeart,
  HiOutlineShieldCheck,
  HiOutlineClock,
  HiOutlineBolt,
  HiOutlineSquares2X2,
  HiOutlineArrowDownTray,
  HiOutlineCommandLine,
  HiOutlineUserGroup,
  HiOutlineTrophy,
  HiOutlineSparkles,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiPython,
  SiC,
  SiMysql,
  SiPhp,
  SiTypescript,
  SiGit,
  SiVercel,
  SiCisco,
  SiWireshark,
  SiNodered,
  SiArduino,
  SiHubspot,
  SiGnubash,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  phone: HiPhone,
  mapPin: HiMapPin,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  academic: HiOutlineAcademicCap,
  briefcase: HiOutlineBriefcase,
  server: HiOutlineServerStack,
  code: HiOutlineCodeBracket,
  chip: HiOutlineCpuChip,
  language: HiOutlineLanguage,
  heart: HiOutlineHeart,
  shield: HiOutlineShieldCheck,
  clock: HiOutlineClock,
  bolt: HiOutlineBolt,
  layers: HiOutlineSquares2X2,
  download: HiOutlineArrowDownTray,
  terminal: HiOutlineCommandLine,
  team: HiOutlineUserGroup,
  trophy: HiOutlineTrophy,
  sparkles: HiOutlineSparkles,
  python: SiPython,
  c: SiC,
  mysql: SiMysql,
  php: SiPhp,
  typescript: SiTypescript,
  git: SiGit,
  vercel: SiVercel,
  cisco: SiCisco,
  wireshark: SiWireshark,
  nodered: SiNodered,
  arduino: SiArduino,
  hubspot: SiHubspot,
  bash: SiGnubash,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
